import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>


        <h2>Next.js Data Fetching examples</h2>

        <div className={styles.grid}>
          <a href="/static-site-generation" className={styles.card}>
            <h2>Static-Site Generation (SSG) &rarr;</h2>
            {/* <p>Find in-depth information about Next.js features and API.</p> */}
          </a>

          <a href="/server-side-rendering" className={styles.card}>
            <h2>Server-Side Rendering (SSR) &rarr;</h2>
            {/* <p>Learn about Next.js in an interactive course with quizzes!</p> */}
          </a>

          <a
            href="/incremental-static-regeneration"
            className={styles.card}
            >
            <h2>Incremental Static Regeneration (ISR) &rarr;</h2>
            {/* <p>Discover and deploy boilerplate example Next.js projects.</p> */}
          </a>

          <a
            href="/client-side-rendering"
            className={styles.card}
            >
            <h2>Client-Side Rendering (CSR) &rarr;</h2>
            {/* <p> Instantly deploy your Next.js site to a public URL with Vercel. </p> */}
          </a>
        </div>
        
        <p className={styles.description}>
          Blog from Guy Dumais ---
          <a href='https://guydumais.digital/blog/next-js-the-ultimate-cheat-sheet-to-page-rendering/'>
            Link</a>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
